// Code generated by 'yaegi extract github.com/suifengpiao14/httpraw'. DO NOT EDIT.

package httpraw

import (
	"reflect"
)

func init() {
	Symbols["github.com/suifengpiao14/httpraw/httpraw"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"SliceAny2string" : reflect.ValueOf(SliceAny2string),
		"DecodeResponseForJsonApiProtocol" : reflect.ValueOf(DecodeResponseForJsonApiProtocol),
		"GetValuesFromJson" : reflect.ValueOf(GetValuesFromJson),
		"SetValueToJson" : reflect.ValueOf(SetValueToJson),
		// type definitions
		"AfterRequestFn":   reflect.ValueOf((*AfterRequestFn)(nil)),
		"BeforRequestFn":   reflect.ValueOf((*BeforeRequestFn)(nil)),
		"RequestDTO":       reflect.ValueOf((*RequestDTO)(nil)),
		"ResponseDTO":      reflect.ValueOf((*ResponseDTO)(nil)),
		
	}
}
